---
- name: ver hostname en todos los hosts
  hosts: all
  become: true
  remote_user: capi

  tasks:
    - name: Ejecutanto hostname
      shell:
        cmd: "hostname"
      register: result

    - name: Mostrar resultado de hostaname
      debug:
        msg: "El número de archivos es {{ result.stdout }}"
