---
- name: Ver hostname en todos los hosts
  hosts: all
  become: true
  remote_user: capi

  tasks:
    - name: Ejecutando hostname
      shell: hostname
      register: result

    - name: Mostrar resultado
      debug:
        var: result.stdout
